"""create matches and deliveries

Revision ID: 7ef908be0530
Revises: 
Create Date: 2026-02-25 23:32:50.183481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef908be0530'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cricsheet_id', sa.String(length=32), nullable=False),
    sa.Column('event_name', sa.String(length=128), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.Column('team1', sa.String(length=64), nullable=True),
    sa.Column('team2', sa.String(length=64), nullable=True),
    sa.Column('venue', sa.String(length=128), nullable=True),
    sa.Column('winner', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cricsheet_id'),
    sa.UniqueConstraint('cricsheet_id', name='uq_matches_cricsheet_id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('innings', sa.SmallInteger(), nullable=False),
    sa.Column('over', sa.SmallInteger(), nullable=False),
    sa.Column('ball', sa.SmallInteger(), nullable=False),
    sa.Column('batting_team', sa.String(length=64), nullable=True),
    sa.Column('bowling_team', sa.String(length=64), nullable=True),
    sa.Column('striker', sa.String(length=80), nullable=True),
    sa.Column('non_striker', sa.String(length=80), nullable=True),
    sa.Column('bowler', sa.String(length=80), nullable=True),
    sa.Column('runs_batter', sa.SmallInteger(), nullable=False),
    sa.Column('runs_extras', sa.SmallInteger(), nullable=False),
    sa.Column('runs_total', sa.SmallInteger(), nullable=False),
    sa.Column('extras_type', sa.String(length=32), nullable=True),
    sa.Column('wicket_kind', sa.String(length=32), nullable=True),
    sa.Column('player_dismissed', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'innings', 'over', 'ball', name='uq_delivery_ball')
    )
    op.create_index('ix_deliveries_match_innings_over', 'deliveries', ['match_id', 'innings', 'over'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deliveries_match_innings_over', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_table('matches')
    # ### end Alembic commands ###
