"""rebuild fantasy with entries

Revision ID: 81893ed6a809
Revises: c69a6133d802
Create Date: 2026-03-01 22:11:04.648528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81893ed6a809'
down_revision: Union[str, Sequence[str], None] = 'c69a6133d802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.Column('rank_global', sa.Integer(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fantasy_entries_id'), 'fantasy_entries', ['id'], unique=False)
    op.add_column('fantasy_team_players', sa.Column('role', sa.String(length=20), nullable=True))
    op.add_column('fantasy_team_players', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fantasy_team_players', 'order')
    op.drop_column('fantasy_team_players', 'role')
    op.drop_index(op.f('ix_fantasy_entries_id'), table_name='fantasy_entries')
    op.drop_table('fantasy_entries')
    # ### end Alembic commands ###
