"""add fantasy teams

Revision ID: 9c2fcafbc90b
Revises: 00ba501a4437
Create Date: 2026-02-26 20:32:48.056315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2fcafbc90b'
down_revision: Union[str, Sequence[str], None] = '00ba501a4437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fantasy_teams_id'), 'fantasy_teams', ['id'], unique=False)
    op.create_table('fantasy_team_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('tournament_year', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fantasy_team_players_id'), 'fantasy_team_players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fantasy_team_players_id'), table_name='fantasy_team_players')
    op.drop_table('fantasy_team_players')
    op.drop_index(op.f('ix_fantasy_teams_id'), table_name='fantasy_teams')
    op.drop_table('fantasy_teams')
    # ### end Alembic commands ###
