"""add match columns

Revision ID: ae4798c905d8
Revises: 7ef908be0530
Create Date: 2026-02-25 23:59:16.235890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4798c905d8'
down_revision: Union[str, Sequence[str], None] = '7ef908be0530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('tournament_year', sa.String(length=4), nullable=True))
    op.add_column('matches', sa.Column('stage', sa.String(length=50), nullable=True))
    op.add_column('matches', sa.Column('toss_winner', sa.String(length=64), nullable=True))
    op.add_column('matches', sa.Column('toss_decision', sa.String(length=10), nullable=True))
    op.add_column('matches', sa.Column('win_by_runs', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('win_by_wickets', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'win_by_wickets')
    op.drop_column('matches', 'win_by_runs')
    op.drop_column('matches', 'toss_decision')
    op.drop_column('matches', 'toss_winner')
    op.drop_column('matches', 'stage')
    op.drop_column('matches', 'tournament_year')
    # ### end Alembic commands ###
