"""update deliveries columns

Revision ID: beff293d8c46
Revises: ae4798c905d8
Create Date: 2026-02-26 00:39:06.353681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beff293d8c46'
down_revision: Union[str, Sequence[str], None] = 'ae4798c905d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('innings_number', sa.SmallInteger(), nullable=False))
    op.add_column('deliveries', sa.Column('ball_in_innings', sa.Integer(), nullable=False))
    op.add_column('deliveries', sa.Column('ball_in_over', sa.SmallInteger(), nullable=False))
    op.add_column('deliveries', sa.Column('batter', sa.String(length=100), nullable=False))
    op.add_column('deliveries', sa.Column('is_legal', sa.Boolean(), nullable=False))
    op.add_column('deliveries', sa.Column('is_wicket', sa.Boolean(), nullable=False))
    op.add_column('deliveries', sa.Column('wicket_type', sa.String(length=50), nullable=True))
    op.add_column('deliveries', sa.Column('dismissed_player', sa.String(length=100), nullable=True))
    op.alter_column('deliveries', 'batting_team',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('deliveries', 'bowling_team',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('deliveries', 'bowler',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('deliveries', 'extras_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_deliveries_match_innings_over'), table_name='deliveries')
    op.drop_constraint(op.f('uq_delivery_ball'), 'deliveries', type_='unique')
    op.create_index('ix_delivery_batter', 'deliveries', ['batter'], unique=False)
    op.create_index('ix_delivery_bowler', 'deliveries', ['bowler'], unique=False)
    op.create_index('ix_delivery_match', 'deliveries', ['match_id'], unique=False)
    op.create_unique_constraint('uq_delivery', 'deliveries', ['match_id', 'innings_number', 'ball_in_innings'])
    op.drop_constraint(op.f('deliveries_match_id_fkey'), 'deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'deliveries', 'matches', ['match_id'], ['id'])
    op.drop_column('deliveries', 'non_striker')
    op.drop_column('deliveries', 'player_dismissed')
    op.drop_column('deliveries', 'striker')
    op.drop_column('deliveries', 'innings')
    op.drop_column('deliveries', 'ball')
    op.drop_column('deliveries', 'wicket_kind')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('wicket_kind', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('ball', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('deliveries', sa.Column('innings', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('deliveries', sa.Column('striker', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('player_dismissed', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('non_striker', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.create_foreign_key(op.f('deliveries_match_id_fkey'), 'deliveries', 'matches', ['match_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_delivery', 'deliveries', type_='unique')
    op.drop_index('ix_delivery_match', table_name='deliveries')
    op.drop_index('ix_delivery_bowler', table_name='deliveries')
    op.drop_index('ix_delivery_batter', table_name='deliveries')
    op.create_unique_constraint(op.f('uq_delivery_ball'), 'deliveries', ['match_id', 'innings', 'over', 'ball'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_deliveries_match_innings_over'), 'deliveries', ['match_id', 'innings', 'over'], unique=False)
    op.alter_column('deliveries', 'extras_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('deliveries', 'bowler',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('deliveries', 'bowling_team',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('deliveries', 'batting_team',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('deliveries', 'dismissed_player')
    op.drop_column('deliveries', 'wicket_type')
    op.drop_column('deliveries', 'is_wicket')
    op.drop_column('deliveries', 'is_legal')
    op.drop_column('deliveries', 'batter')
    op.drop_column('deliveries', 'ball_in_over')
    op.drop_column('deliveries', 'ball_in_innings')
    op.drop_column('deliveries', 'innings_number')
    # ### end Alembic commands ###
