"""add match_id to fantasy_teams

Revision ID: e215f3452104
Revises: 439d8e00b688
Create Date: 2026-03-02 00:56:05.622959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e215f3452104'
down_revision: Union[str, Sequence[str], None] = '439d8e00b688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fantasy_teams', sa.Column('match_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fantasy_teams', 'matches', ['match_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fantasy_teams', type_='foreignkey')
    op.drop_column('fantasy_teams', 'match_id')
    # ### end Alembic commands ###
